image: go1.3
git:
  path: github.com/devastation007/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - go get
  - go build
  - go test -short

notify:
  email:
    recipients:
      - m.froechtenicht@gmail.com